# ============================================================
# PROJECT 02
# PORTFOLIO RISK & PERFORMANCE ANALYTICS
# ============================================================
#
# Purpose:
# Analyse portfolio risk and performance using the processed
# market data created in Project 01.
#
# The project demonstrates:
#   - Portfolio return calculation
#   - Portfolio volatility
#   - Sharpe ratio
#   - Maximum drawdown
#   - Covariance matrix
#   - Correlation matrix
#   - Value at Risk (VaR)
#   - Expected Shortfall (ES)
#   - Asset beta relative to the S&P 500
#   - Portfolio beta
#   - Benchmark comparison
#
# Project 02 deliberately does NOT download raw market data.
# It reuses the processed data generated by Project 01.
# ============================================================


# ------------------------------------------------------------
# 1. IMPORT LIBRARIES
# ------------------------------------------------------------

import os
import numpy as np
import pandas as pd


# ------------------------------------------------------------
# 2. PROJECT SETTINGS
# ------------------------------------------------------------

ASSETS = [
    "AAPL",
    "MSFT",
    "NVDA",
    "GOOG",
    "META"
]

BENCHMARK = "^GSPC"

TRADING_DAYS = 252

CONFIDENCE_LEVEL = 0.95

INITIAL_WEALTH = 1.0


# ------------------------------------------------------------
# 3. LOAD PROCESSED PRICE DATA
# ------------------------------------------------------------
#
# Project 01 creates:
#
# ../data/processed_prices.csv
#
# Project 02 reads that file rather than downloading
# the data again.
# ------------------------------------------------------------

DATA_PATH = "../data/processed_prices.csv"

if not os.path.exists(DATA_PATH):
    raise FileNotFoundError(
        f"Processed price data not found: {DATA_PATH}\n"
        "Run Project 01 first and create processed_prices.csv."
    )


prices = pd.read_csv(
    DATA_PATH,
    index_col=0,
    parse_dates=True
)


# ------------------------------------------------------------
# 4. KEEP REQUIRED ASSETS
# ------------------------------------------------------------

missing_assets = [
    asset
    for asset in ASSETS
    if asset not in prices.columns
]

if missing_assets:
    raise ValueError(
        f"Missing required assets: {missing_assets}"
    )


prices = prices[ASSETS].copy()


# ------------------------------------------------------------
# 5. CALCULATE DAILY RETURNS
# ------------------------------------------------------------

returns = (
    prices
    .pct_change()
    .dropna()
)


# ------------------------------------------------------------
# 6. OPTIONAL BENCHMARK DATA
# ------------------------------------------------------------
#
# If Project 01 saved the S&P 500 together with the prices,
# use it.
#
# Otherwise Project 02 can still perform all portfolio-risk
# analysis except benchmark-specific calculations.
# ------------------------------------------------------------

benchmark_returns = None

benchmark_path = "../data/processed_benchmark.csv"

if os.path.exists(benchmark_path):

    benchmark_prices = pd.read_csv(
        benchmark_path,
        index_col=0,
        parse_dates=True
    )

    if BENCHMARK in benchmark_prices.columns:

        benchmark_prices = (
            benchmark_prices[BENCHMARK]
        )

        benchmark_returns = (
            benchmark_prices
            .pct_change()
            .dropna()
        )

elif BENCHMARK in prices.columns:

    benchmark_prices = prices[BENCHMARK]

    benchmark_returns = (
        benchmark_prices
        .pct_change()
        .dropna()
    )


# ------------------------------------------------------------
# 7. DATA INSPECTION
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("PROJECT 02 — PORTFOLIO RISK & PERFORMANCE ANALYTICS")
print("=" * 60)

print("\n--- LOADED PRICE DATA ---")
print(prices.head())

print("\nStart:", prices.index.min())
print("End:", prices.index.max())
print("Observations:", len(prices))
print("Assets:", list(prices.columns))


print("\n--- PORTFOLIO DAILY RETURNS ---")
print(returns.head())

print("\nReturn observations:", len(returns))


# ------------------------------------------------------------
# 8. DATA QUALITY CHECK
# ------------------------------------------------------------

print("\n--- DATA CHECK ---")

print(
    "Price observations:",
    len(prices)
)

print(
    "Return observations:",
    len(returns)
)

print(
    "Missing price values:",
    prices.isna().sum().sum()
)

print(
    "Missing return values:",
    returns.isna().sum().sum()
)


# ------------------------------------------------------------
# 9. EQUAL-WEIGHT PORTFOLIO
# ------------------------------------------------------------
#
# Each asset receives an equal allocation.
#
# For five assets:
#
# Weight = 1 / 5 = 20%
# ------------------------------------------------------------

weights = pd.Series(
    1 / len(ASSETS),
    index=ASSETS
)


print("\n--- PORTFOLIO WEIGHTS ---")

print(weights)

print(
    "\nWeight Sum:",
    weights.sum()
)


# ------------------------------------------------------------
# 10. PORTFOLIO DAILY RETURNS
# ------------------------------------------------------------

portfolio_returns = (
    returns
    .dot(weights)
)


print("\n--- PORTFOLIO DAILY RETURNS ---")

print(
    portfolio_returns.head()
)


# ------------------------------------------------------------
# 11. CUMULATIVE PORTFOLIO WEALTH
# ------------------------------------------------------------

portfolio_wealth = (
    INITIAL_WEALTH
    * (1 + portfolio_returns).cumprod()
)


print("\n--- PORTFOLIO WEALTH ---")

print(
    portfolio_wealth.head()
)

print(
    "\nFinal Wealth:",
    portfolio_wealth.iloc[-1]
)


# ------------------------------------------------------------
# 12. TOTAL RETURN
# ------------------------------------------------------------

total_return = (
    portfolio_wealth.iloc[-1]
    / INITIAL_WEALTH
    - 1
)


# ------------------------------------------------------------
# 13. ANNUALIZED RETURN
# ------------------------------------------------------------

number_of_days = len(portfolio_returns)

annualized_return = (
    (1 + total_return)
    ** (TRADING_DAYS / number_of_days)
    - 1
)


# ------------------------------------------------------------
# 14. ANNUALIZED VOLATILITY
# ------------------------------------------------------------

annualized_volatility = (
    portfolio_returns.std()
    * np.sqrt(TRADING_DAYS)
)


# ------------------------------------------------------------
# 15. SHARPE RATIO
# ------------------------------------------------------------
#
# For this project we assume a zero risk-free rate.
#
# Sharpe =
# Annualized Return / Annualized Volatility
# ------------------------------------------------------------

if annualized_volatility != 0:

    sharpe_ratio = (
        annualized_return
        / annualized_volatility
    )

else:

    sharpe_ratio = np.nan


# ------------------------------------------------------------
# 16. MAXIMUM DRAWDOWN
# ------------------------------------------------------------

running_max = (
    portfolio_wealth
    .cummax()
)

drawdown = (
    portfolio_wealth / running_max
    - 1
)

maximum_drawdown = (
    drawdown.min()
)


# ------------------------------------------------------------
# 17. BASIC PERFORMANCE SUMMARY
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("PORTFOLIO PERFORMANCE")
print("=" * 60)

print(
    f"Total Return:          {total_return:.4f}"
)

print(
    f"Annualized Return:     {annualized_return:.4f}"
)

print(
    f"Annualized Volatility: {annualized_volatility:.4f}"
)

print(
    f"Sharpe Ratio:          {sharpe_ratio:.4f}"
)

print(
    f"Maximum Drawdown:      {maximum_drawdown:.4f}"
)

print(
    f"Final Wealth:          {portfolio_wealth.iloc[-1]:.4f}"
)


# ------------------------------------------------------------
# 18. COVARIANCE MATRIX
# ------------------------------------------------------------
#
# Daily covariance is annualized by multiplying by 252.
# ------------------------------------------------------------

covariance_matrix = (
    returns
    .cov()
    * TRADING_DAYS
)


print("\n" + "=" * 60)
print("ANNUALIZED COVARIANCE MATRIX")
print("=" * 60)

print(
    covariance_matrix
)


# ------------------------------------------------------------
# 19. CORRELATION MATRIX
# ------------------------------------------------------------

correlation_matrix = (
    returns
    .corr()
)


print("\n" + "=" * 60)
print("CORRELATION MATRIX")
print("=" * 60)

print(
    correlation_matrix
)


# ------------------------------------------------------------
# 20. PORTFOLIO VARIANCE
# ------------------------------------------------------------
#
# Portfolio variance:
#
# σ²p = w' Σ w
#
# where:
#   w = portfolio weights
#   Σ = covariance matrix
# ------------------------------------------------------------

weight_array = weights.values

portfolio_variance = (
    weight_array
    @ covariance_matrix.values
    @ weight_array
)


# ------------------------------------------------------------
# 21. PORTFOLIO VOLATILITY FROM COVARIANCE MATRIX
# ------------------------------------------------------------

portfolio_volatility_matrix = (
    np.sqrt(portfolio_variance)
)


print("\n" + "=" * 60)
print("PORTFOLIO RISK FROM COVARIANCE MATRIX")
print("=" * 60)

print(
    "Portfolio Variance:",
    portfolio_variance
)

print(
    "Portfolio Volatility:",
    portfolio_volatility_matrix
)


# ------------------------------------------------------------
# 22. VALUE AT RISK — HISTORICAL METHOD
# ------------------------------------------------------------
#
# Historical VaR at 95% confidence uses the 5th percentile
# of the observed portfolio-return distribution.
#
# VaR is reported as a positive loss number.
# ------------------------------------------------------------

var_percentile = (
    np.percentile(
        portfolio_returns,
        (1 - CONFIDENCE_LEVEL) * 100
    )
)

historical_var = -var_percentile


print("\n" + "=" * 60)
print("HISTORICAL VALUE AT RISK")
print("=" * 60)

print(
    f"Confidence Level: {CONFIDENCE_LEVEL:.0%}"
)

print(
    f"Daily VaR:         {historical_var:.4f}"
)


# ------------------------------------------------------------
# 23. EXPECTED SHORTFALL
# ------------------------------------------------------------
#
# Expected Shortfall measures the average loss when returns
# fall beyond the VaR threshold.
# ------------------------------------------------------------

tail_returns = (
    portfolio_returns[
        portfolio_returns
        <= var_percentile
    ]
)

expected_shortfall = (
    -tail_returns.mean()
)


print("\n" + "=" * 60)
print("EXPECTED SHORTFALL")
print("=" * 60)

print(
    f"Daily Expected Shortfall: "
    f"{expected_shortfall:.4f}"
)


# ------------------------------------------------------------
# 24. INDIVIDUAL ASSET RISK
# ------------------------------------------------------------

asset_risk_summary = pd.DataFrame(
    index=ASSETS
)

asset_risk_summary["Annualized_Return"] = (
    returns.mean()
    * TRADING_DAYS
)

asset_risk_summary["Annualized_Volatility"] = (
    returns.std()
    * np.sqrt(TRADING_DAYS)
)

asset_risk_summary["Sharpe_Ratio"] = (
    asset_risk_summary["Annualized_Return"]
    /
    asset_risk_summary["Annualized_Volatility"]
)


print("\n" + "=" * 60)
print("INDIVIDUAL ASSET RISK & PERFORMANCE")
print("=" * 60)

print(
    asset_risk_summary
)


# ------------------------------------------------------------
# 25. ASSET BETA
# ------------------------------------------------------------
#
# Beta measures sensitivity to the market:
#
# Beta_i =
# Cov(R_i, R_m) / Var(R_m)
#
# where R_m is the benchmark return.
# ------------------------------------------------------------

if benchmark_returns is not None:

    beta_data = pd.concat(
        [
            returns,
            benchmark_returns.rename(BENCHMARK)
        ],
        axis=1
    ).dropna()

    benchmark_variance = (
        beta_data[BENCHMARK]
        .var()
    )

    asset_betas = {}

    for asset in ASSETS:

        covariance = (
            beta_data[asset]
            .cov(
                beta_data[BENCHMARK]
            )
        )

        asset_betas[asset] = (
            covariance
            / benchmark_variance
        )

    asset_betas = pd.Series(
        asset_betas,
        name="Beta"
    )


    print("\n" + "=" * 60)
    print("ASSET BETAS")
    print("=" * 60)

    print(
        asset_betas
    )


    # --------------------------------------------------------
    # 26. PORTFOLIO BETA
    # --------------------------------------------------------

    portfolio_beta = (
        weights
        .dot(asset_betas)
    )


    print(
        "\nPortfolio Beta:",
        portfolio_beta
    )


# ------------------------------------------------------------
# 27. BENCHMARK PERFORMANCE
# ------------------------------------------------------------

if benchmark_returns is not None:

    benchmark_wealth = (
        INITIAL_WEALTH
        * (1 + benchmark_returns)
        .cumprod()
    )

    benchmark_total_return = (
        benchmark_wealth.iloc[-1]
        - 1
    )


    print("\n" + "=" * 60)
    print("BENCHMARK PERFORMANCE")
    print("=" * 60)

    print(
        "Benchmark:",
        BENCHMARK
    )

    print(
        "Benchmark Total Return:",
        benchmark_total_return
    )


    # --------------------------------------------------------
    # 28. PORTFOLIO VS BENCHMARK
    # --------------------------------------------------------

    comparison = pd.concat(
        [
            portfolio_returns.rename("Portfolio"),
            benchmark_returns.rename("Benchmark")
        ],
        axis=1
    ).dropna()


    active_returns = (
        comparison["Portfolio"]
        - comparison["Benchmark"]
    )


    active_total_return = (
        (1 + active_returns).prod()
        - 1
    )


    tracking_error = (
        active_returns.std()
        * np.sqrt(TRADING_DAYS)
    )


    if tracking_error != 0:

        information_ratio = (
            active_returns.mean()
            * TRADING_DAYS
            / tracking_error
        )

    else:

        information_ratio = np.nan


    print("\n" + "=" * 60)
    print("BENCHMARK RELATIVE PERFORMANCE")
    print("=" * 60)

    print(
        "Active Total Return:",
        active_total_return
    )

    print(
        "Tracking Error:",
        tracking_error
    )

    print(
        "Information Ratio:",
        information_ratio
    )


# ------------------------------------------------------------
# 29. RISK CONTRIBUTION
# ------------------------------------------------------------
#
# Marginal risk contribution:
#
# MRC_i = (Σw)_i / Portfolio Volatility
#
# Component risk contribution:
#
# CRC_i = w_i × MRC_i
#
# Percentage risk contribution:
#
# CRC_i / Portfolio Volatility
# ------------------------------------------------------------

sigma_w = (
    covariance_matrix.values
    @ weight_array
)

portfolio_volatility = (
    np.sqrt(portfolio_variance)
)

marginal_risk_contribution = (
    sigma_w
    / portfolio_volatility
)

component_risk_contribution = (
    weight_array
    * marginal_risk_contribution
)

risk_contribution_percentage = (
    component_risk_contribution
    / portfolio_volatility
)


risk_contribution = pd.DataFrame({

    "Weight": weight_array,

    "Marginal_Risk_Contribution":
        marginal_risk_contribution,

    "Component_Risk_Contribution":
        component_risk_contribution,

    "Risk_Contribution_%":
        risk_contribution_percentage * 100

}, index=ASSETS)


print("\n" + "=" * 60)
print("PORTFOLIO RISK CONTRIBUTION")
print("=" * 60)

print(
    risk_contribution
)

print(
    "\nTotal Risk Contribution:",
    risk_contribution_percentage.sum()
)


# ------------------------------------------------------------
# 30. FINAL SUMMARY
# ------------------------------------------------------------

summary = pd.Series({

    "Total_Return":
        total_return,

    "Annualized_Return":
        annualized_return,

    "Annualized_Volatility":
        annualized_volatility,

    "Sharpe_Ratio":
        sharpe_ratio,

    "Maximum_Drawdown":
        maximum_drawdown,

    "Daily_VaR_95%":
        historical_var,

    "Daily_Expected_Shortfall":
        expected_shortfall,

    "Portfolio_Variance":
        portfolio_variance,

    "Portfolio_Volatility":
        portfolio_volatility_matrix

})


print("\n" + "=" * 60)
print("FINAL PORTFOLIO RISK SUMMARY")
print("=" * 60)

print(
    summary
)


# ------------------------------------------------------------
# 31. SAVE PROJECT 02 OUTPUTS
# ------------------------------------------------------------
#
# These files allow the analysis to be inspected without
# rerunning the entire project.
# ------------------------------------------------------------

OUTPUT_PATH = "../outputs"

os.makedirs(
    OUTPUT_PATH,
    exist_ok=True
)


asset_risk_summary.to_csv(
    f"{OUTPUT_PATH}/asset_risk_summary.csv"
)

covariance_matrix.to_csv(
    f"{OUTPUT_PATH}/covariance_matrix.csv"
)

correlation_matrix.to_csv(
    f"{OUTPUT_PATH}/correlation_matrix.csv"
)

risk_contribution.to_csv(
    f"{OUTPUT_PATH}/risk_contribution.csv"
)

portfolio_returns.to_csv(
    f"{OUTPUT_PATH}/portfolio_daily_returns.csv",
    header=True
)

portfolio_wealth.to_csv(
    f"{OUTPUT_PATH}/portfolio_wealth.csv",
    header=True
)

summary.to_csv(
    f"{OUTPUT_PATH}/portfolio_risk_summary.csv",
    header=True
)


print("\n" + "=" * 60)
print("PROJECT 02 OUTPUTS SAVED")
print("=" * 60)

print(
    "Output directory:",
    OUTPUT_PATH
)

print(
    "Project 02 completed successfully."
)
