# ============================================================
# PROJECT 02
# PORTFOLIO RISK & PERFORMANCE ANALYTICS
# ============================================================
#
# OBJECTIVE
# ------------------------------------------------------------
# Analyse the risk and performance of two frozen portfolios
# produced by Project 01:
#
#   1. Equal-weight benchmark
#   2. Max-40 constrained alternative model
#
# Project 02 does NOT:
#
#   - select assets
#   - calculate factors
#   - optimize parameters
#   - optimize portfolio weights
#   - generate trading signals
#   - perform short-term trading
#
# Project 02 consumes the outputs of Project 01 and performs:
#
#   - Portfolio performance analysis
#   - Active return analysis
#   - Active weight analysis
#   - Tracking error
#   - Information ratio
#   - Portfolio risk contribution
#   - Performance attribution
#   - Historical Value at Risk (VaR)
#   - Expected Shortfall (ES)
#
# The purpose of Project 02 is to answer:
#
#   "How does the Project 01 portfolio behave as a
#    long-term investment, in terms of return and risk?"
#
# ============================================================


# ============================================================
# 1. IMPORT LIBRARIES
# ============================================================

import os

import numpy as np
import pandas as pd


# ============================================================
# 2. PROJECT SETTINGS
# ============================================================

TRADING_DAYS = 252

RISK_FREE_RATE = 0.0

VAR_CONFIDENCE = 0.95


# ============================================================
# 3. PORTABLE PROJECT PATHS
# ============================================================
#
# The script is located inside the Project 02 directory.
#
# Therefore:
#
#     PROJECT_PATH
#          |
#          ├── data
#          ├── outputs
#          └── portfolio_risk_performance.py
#
# This makes the project portable across:
#
#     - Windows
#     - Linux
#     - macOS
#     - GitHub Codespaces
#     - other Python environments
#
# No Pydroid/Android-specific paths are used.
# ============================================================

PROJECT_PATH = os.path.dirname(
    os.path.abspath(__file__)
)


# ============================================================
# 4. DATA AND OUTPUT PATHS
# ============================================================

DATA_PATH = os.path.join(
    PROJECT_PATH,
    "data"
)

PROJECT_02_OUTPUT = os.path.join(
    PROJECT_PATH,
    "outputs"
)

os.makedirs(
    PROJECT_02_OUTPUT,
    exist_ok=True
)


# ============================================================
# 5. FILE PATHS
# ============================================================
#
# These files were generated by Project 01 and transferred
# into the Project 02 data folder.
#
# Project 02 therefore consumes frozen Project 01 outputs
# rather than recreating Project 01 calculations.
# ============================================================

PROCESSED_PRICES_FILE = os.path.join(
    DATA_PATH,
    "processed_prices.csv"
)

FINAL_TEST_RETURNS_FILE = os.path.join(
    DATA_PATH,
    "final_test_returns.csv"
)

FROZEN_PORTFOLIOS_FILE = os.path.join(
    DATA_PATH,
    "frozen_portfolios.csv"
)

FINAL_OOS_RESULTS_FILE = os.path.join(
    DATA_PATH,
    "final_oos_results.csv"
)


# ============================================================
# 6. CHECK PROJECT 01 INPUT FILES
# ============================================================

required_files = [

    PROCESSED_PRICES_FILE,

    FINAL_TEST_RETURNS_FILE,

    FROZEN_PORTFOLIOS_FILE,

    FINAL_OOS_RESULTS_FILE
]


print(
    "\n" + "=" * 70
)

print(
    "PROJECT 02 — CHECKING INPUT DATA"
)

print(
    "=" * 70
)


print(
    "\nProject path:"
)

print(
    PROJECT_PATH
)


print(
    "\nData path:"
)

print(
    DATA_PATH
)


print(
    "\nOutput path:"
)

print(
    PROJECT_02_OUTPUT
)


for file_path in required_files:

    if not os.path.exists(file_path):

        raise FileNotFoundError(
            f"\nRequired Project 01 input not found:\n"
            f"{file_path}"
        )

    print(
        "✓ Found:",
        os.path.basename(file_path)
    )


print(
    "\nAll required Project 01 inputs found."
)


# ============================================================
# 7. LOAD CLEANED PRICES
# ============================================================
#
# This demonstrates that Project 02 receives cleaned data
# from Project 01 rather than repeating raw-data preparation.
# ============================================================

processed_prices = pd.read_csv(

    PROCESSED_PRICES_FILE,

    index_col=0,

    parse_dates=True
)


print(
    "\n" + "=" * 70
)

print(
    "LOADING CLEANED PRICES"
)

print(
    "=" * 70
)


print(
    "\nProcessed prices loaded:"
)

print(
    processed_prices.shape
)


# ============================================================
# 8. LOAD FINAL OOS RETURNS
# ============================================================
#
# These are the returns of the selected assets during the
# genuinely unseen test period identified by Project 01.
#
# Project 02 uses this period to evaluate the frozen
# portfolios without re-estimating their weights.
# ============================================================

final_test_returns = pd.read_csv(

    FINAL_TEST_RETURNS_FILE,

    index_col=0,

    parse_dates=True
)


print(
    "\nFinal OOS returns loaded:"
)

print(
    final_test_returns.shape
)


print(
    "\nFinal OOS period:"
)

print(
    final_test_returns.index.min(),
    "to",
    final_test_returns.index.max()
)


# ============================================================
# 9. LOAD FROZEN PORTFOLIOS
# ============================================================
#
# These portfolio weights originate from Project 01.
#
# Project 02 does not modify them.
# ============================================================

frozen_portfolios = pd.read_csv(

    FROZEN_PORTFOLIOS_FILE,

    index_col=0
)


print(
    "\nFrozen portfolios loaded:"
)

print(
    frozen_portfolios
)


# ============================================================
# 10. LOAD PROJECT 01 OOS RESULTS
# ============================================================
#
# This is used for cross-checking that Project 02 is analysing
# the same portfolios that Project 01 evaluated.
# ============================================================

project_01_oos_results = pd.read_csv(

    FINAL_OOS_RESULTS_FILE
)


print(
    "\nProject 01 OOS results loaded:"
)

print(
    project_01_oos_results
)


# ============================================================
# 11. IDENTIFY THE TWO PORTFOLIOS
# ============================================================

required_portfolios = [

    "Equal_Weight",

    "Max_40"
]


for portfolio in required_portfolios:

    if portfolio not in frozen_portfolios.index:

        raise ValueError(
            f"{portfolio} is missing from frozen portfolios."
        )


benchmark_weights = (

    frozen_portfolios

    .loc["Equal_Weight"]

    .astype(float)
)


alternative_weights = (

    frozen_portfolios

    .loc["Max_40"]

    .astype(float)
)


# ============================================================
# 12. ALIGN WEIGHTS WITH RETURNS
# ============================================================

common_assets = (

    final_test_returns.columns

    .intersection(
        benchmark_weights.index
    )
)


if len(common_assets) == 0:

    raise ValueError(
        "No common assets between Project 01 returns "
        "and frozen portfolio weights."
    )


final_test_returns = (

    final_test_returns[
        common_assets
    ]
)


benchmark_weights = (

    benchmark_weights[
        common_assets
    ]
)


alternative_weights = (

    alternative_weights[
        common_assets
    ]
)


# ============================================================
# 13. WEIGHT CHECK
# ============================================================

if not np.isclose(

    benchmark_weights.sum(),

    1.0

):

    raise ValueError(
        "Equal-weight portfolio does not sum to 1."
    )


if not np.isclose(

    alternative_weights.sum(),

    1.0

):

    raise ValueError(
        "Alternative portfolio does not sum to 1."
    )


print(
    "\n" + "=" * 70
)

print(
    "PORTFOLIO DEFINITIONS"
)

print(
    "=" * 70
)


print(
    "\nBenchmark — Equal Weight:"
)

print(
    benchmark_weights
)


print(
    "\nAlternative — Max 40:"
)

print(
    alternative_weights
)


# ============================================================
# 14. PORTFOLIO RETURNS
# ============================================================
#
# Portfolio return:
#
#       R_p,t = Σ w_i R_i,t
#
# implemented using:
#
#       returns.dot(weights)
#
# ============================================================

benchmark_returns = (

    final_test_returns

    .dot(
        benchmark_weights
    )
)


alternative_returns = (

    final_test_returns

    .dot(
        alternative_weights
    )
)


# ============================================================
# 15. BASIC PERFORMANCE FUNCTION
# ============================================================

def evaluate_portfolio(
    portfolio_returns
):

    """
    Calculate absolute portfolio performance metrics.
    """

    portfolio_returns = (

        portfolio_returns

        .dropna()
    )


    total_return = (

        (1 + portfolio_returns)

        .prod()

        - 1
    )


    annualized_return = (

        (1 + total_return)

        ** (

            TRADING_DAYS
            /
            len(portfolio_returns)

        )

        - 1
    )


    annualized_volatility = (

        portfolio_returns.std()

        *
        np.sqrt(
            TRADING_DAYS
        )
    )


    if annualized_volatility != 0:

        sharpe = (

            annualized_return
            -
            RISK_FREE_RATE

        ) / annualized_volatility

    else:

        sharpe = np.nan


    wealth = (

        1 + portfolio_returns

    ).cumprod()


    drawdown = (

        wealth

        /

        wealth.cummax()

        - 1
    )


    maximum_drawdown = (

        drawdown.min()
    )


    return {

        "Total_Return":
            total_return,

        "Annualized_Return":
            annualized_return,

        "Annualized_Volatility":
            annualized_volatility,

        "Sharpe_Ratio":
            sharpe,

        "Maximum_Drawdown":
            maximum_drawdown,

        "Final_Wealth":
            wealth.iloc[-1]
    }


# ============================================================
# 16. PERFORMANCE COMPARISON
# ============================================================

benchmark_metrics = (

    evaluate_portfolio(

        benchmark_returns
    )
)


alternative_metrics = (

    evaluate_portfolio(

        alternative_returns
    )
)


performance_comparison = pd.DataFrame(

    [

        {

            "Portfolio":
                "Equal_Weight",

            **benchmark_metrics

        },

        {

            "Portfolio":
                "Max_40",

            **alternative_metrics

        }

    ]
)


print(
    "\n" + "=" * 70
)

print(
    "PORTFOLIO PERFORMANCE COMPARISON"
)

print(
    "=" * 70
)

print(
    performance_comparison
)


# ============================================================
# 17. ACTIVE RETURN
# ============================================================
#
# Daily active return:
#
#       R_A,t = R_P,t - R_B,t
#
# where:
#
#       R_P,t = alternative portfolio return
#       R_B,t = equal-weight benchmark return
#
# ============================================================

active_returns = (

    alternative_returns

    -

    benchmark_returns
)


active_total_return = (

    (1 + active_returns)

    .prod()

    - 1
)


# Arithmetic annualised active return
#
# This is the annualised mean daily active return.
# It is used with annualised tracking error for the
# Information Ratio.

annualized_arithmetic_active_return = (

    active_returns.mean()

    *
    TRADING_DAYS
)


print(
    "\n" + "=" * 70
)

print(
    "ACTIVE RETURN ANALYSIS"
)

print(
    "=" * 70
)


print(
    "\nAlternative total return:",
    alternative_metrics["Total_Return"]
)


print(
    "Benchmark total return:",
    benchmark_metrics["Total_Return"]
)


print(
    "Active total return:",
    active_total_return
)


print(
    "Annualized arithmetic active return:",
    annualized_arithmetic_active_return
)


# ============================================================
# 18. ACTIVE WEIGHTS
# ============================================================
#
# Active weight:
#
#       Active Weight_i
#       =
#       Alternative Weight_i
#       -
#       Benchmark Weight_i
#
# ============================================================

active_weights = (

    alternative_weights

    -

    benchmark_weights
)


active_weight_table = pd.DataFrame({

    "Alternative_Weight":
        alternative_weights,

    "Benchmark_Weight":
        benchmark_weights,

    "Active_Weight":
        active_weights
})


print(
    "\n" + "=" * 70
)

print(
    "ACTIVE WEIGHTS"
)

print(
    "=" * 70
)


print(
    active_weight_table
)


print(
    "\nActive weight sum:",
    active_weights.sum()
)


# ============================================================
# 19. TRACKING ERROR
# ============================================================
#
# Tracking Error is the standard deviation of active returns.
#
#       TE_daily = std(R_A)
#
#       TE_annual = TE_daily × sqrt(252)
#
# ============================================================

daily_tracking_error = (

    active_returns.std()
)


annualized_tracking_error = (

    daily_tracking_error

    *
    np.sqrt(
        TRADING_DAYS
    )
)


print(
    "\n" + "=" * 70
)

print(
    "TRACKING ERROR"
)

print(
    "=" * 70
)


print(
    "Daily tracking error:",
    daily_tracking_error
)


print(
    "Annualized tracking error:",
    annualized_tracking_error
)


# ============================================================
# 20. INFORMATION RATIO
# ============================================================
#
#       IR =
#
#       Annualised Active Return
#       ------------------------
#       Annualised Tracking Error
#
# ============================================================

if annualized_tracking_error != 0:

    information_ratio = (

        annualized_arithmetic_active_return

        /

        annualized_tracking_error
    )

else:

    information_ratio = np.nan


print(
    "\n" + "=" * 70
)

print(
    "INFORMATION RATIO"
)

print(
    "=" * 70
)


print(
    "Information Ratio:",
    information_ratio
)


# ============================================================
# 21. OOS COVARIANCE MATRIX
# ============================================================
#
# Project 02 calculates risk characteristics using the final
# unseen period.
#
# Annualised covariance:
#
#       Σ_annual = Σ_daily × 252
#
# ============================================================

oos_covariance = (

    final_test_returns

    .cov()

    *
    TRADING_DAYS
)


print(
    "\n" + "=" * 70
)

print(
    "FINAL OOS ANNUALIZED COVARIANCE MATRIX"
)

print(
    "=" * 70
)


print(
    oos_covariance
)


# ============================================================
# 22. ALTERNATIVE PORTFOLIO RISK CONTRIBUTION
# ============================================================
#
# Portfolio variance:
#
#       σ_p² = w'Σw
#
# Portfolio volatility:
#
#       σ_p = sqrt(w'Σw)
#
# Marginal Risk Contribution:
#
#       MRC_i = (Σw)_i / σ_p
#
# Component Risk Contribution:
#
#       CRC_i = w_i × MRC_i
#
# ============================================================

alternative_weight_array = (

    alternative_weights.values
)


covariance_matrix = (

    oos_covariance.values
)


portfolio_variance = (

    alternative_weight_array

    @

    covariance_matrix

    @

    alternative_weight_array
)


portfolio_volatility = (

    np.sqrt(
        portfolio_variance
    )
)


sigma_w = (

    covariance_matrix

    @

    alternative_weight_array
)


marginal_risk_contribution = (

    sigma_w

    /

    portfolio_volatility
)


component_risk_contribution = (

    alternative_weight_array

    *

    marginal_risk_contribution
)


risk_contribution_percentage = (

    component_risk_contribution

    /

    portfolio_volatility
)


risk_contribution = pd.DataFrame({

    "Weight":
        alternative_weight_array,

    "Marginal_Risk_Contribution":
        marginal_risk_contribution,

    "Component_Risk_Contribution":
        component_risk_contribution,

    "Risk_Contribution_%":
        risk_contribution_percentage
        *
        100

}, index=common_assets)


print(
    "\n" + "=" * 70
)

print(
    "ALTERNATIVE PORTFOLIO RISK CONTRIBUTION"
)

print(
    "=" * 70
)


print(
    risk_contribution
)


print(
    "\nRisk contribution sum:",
    risk_contribution_percentage.sum()
)


# ============================================================
# 23. PERFORMANCE ATTRIBUTION
# ============================================================
#
# Simplified cumulative active contribution:
#
#       Active Contribution_i
#       =
#       Active Weight_i × Asset Return_i
#
# This provides an intuitive decomposition of active
# performance.
#
# Daily attribution is used as the primary attribution
# framework because daily active contributions aggregate
# naturally through time.
# ============================================================

asset_oos_returns = (

    (

        final_test_returns

        + 1

    )

    .prod()

    - 1
)


active_contribution = (

    active_weights

    *

    asset_oos_returns
)


performance_attribution = pd.DataFrame({

    "Benchmark_Weight":
        benchmark_weights,

    "Alternative_Weight":
        alternative_weights,

    "Active_Weight":
        active_weights,

    "Asset_OOS_Return":
        asset_oos_returns,

    "Active_Contribution":
        active_contribution
})


print(
    "\n" + "=" * 70
)

print(
    "PERFORMANCE ATTRIBUTION"
)

print(
    "=" * 70
)


print(
    performance_attribution
)


print(
    "\nSum of simplified active contributions:",
    active_contribution.sum()
)


print(
    "Actual compounded active return:",
    active_total_return
)


# ============================================================
# 24. DAILY PERFORMANCE ATTRIBUTION
# ============================================================
#
# Daily active contribution:
#
#       AC_i,t = Active Weight_i × Asset Return_i,t
#
# Total daily active return:
#
#       AR_t = Σ AC_i,t
#
# ============================================================

daily_active_contribution = (

    final_test_returns

    .mul(

        active_weights,

        axis=1

    )
)


daily_active_contribution[
    "Total_Active_Return"
] = (

    daily_active_contribution

    .sum(

        axis=1

    )
)


# ============================================================
# 25. HISTORICAL VALUE AT RISK
# ============================================================
#
# Historical VaR estimates the return threshold associated
# with the lower tail of the historical return distribution.
#
# For a 95% confidence level:
#
#       VaR threshold = 5th percentile of returns
#
# Example:
#
#       VaR = -0.025
#
# means the 5th percentile historical daily return was -2.5%.
#
# IMPORTANT:
#
# The value is expressed as a RETURN, so negative values
# represent losses.
# ============================================================

def historical_var(

    portfolio_returns,

    confidence=VAR_CONFIDENCE

):

    """
    Calculate historical Value at Risk as a return threshold.

    A 95% VaR corresponds to the 5th percentile of returns.
    """

    portfolio_returns = (

        portfolio_returns

        .dropna()
    )


    var = (

        portfolio_returns

        .quantile(
            1 - confidence
        )
    )


    return var


# ============================================================
# 26. EXPECTED SHORTFALL
# ============================================================
#
# Expected Shortfall measures the average return in the
# worst tail beyond the VaR threshold.
#
# For 95% confidence:
#
#       ES = mean(returns <= VaR)
#
# Therefore ES should normally be equal to or more negative
# than VaR.
# ============================================================

def historical_es(

    portfolio_returns,

    confidence=VAR_CONFIDENCE

):

    """
    Calculate historical Expected Shortfall.

    ES is the average portfolio return in observations
    that are at or below the historical VaR threshold.
    """

    portfolio_returns = (

        portfolio_returns

        .dropna()
    )


    var = historical_var(

        portfolio_returns,

        confidence
    )


    tail_losses = (

        portfolio_returns[
            portfolio_returns <= var
        ]
    )


    if len(tail_losses) == 0:

        return np.nan


    es = tail_losses.mean()


    return es


# ============================================================
# 27. CALCULATE VaR AND ES FOR BOTH PORTFOLIOS
# ============================================================

benchmark_var = historical_var(

    benchmark_returns
)


benchmark_es = historical_es(

    benchmark_returns
)


alternative_var = historical_var(

    alternative_returns
)


alternative_es = historical_es(

    alternative_returns
)


print(
    "\n" + "=" * 70
)

print(
    "TAIL RISK ANALYSIS"
)

print(
    "=" * 70
)


print(
    "\nHistorical VaR and Expected Shortfall"
)


print(
    "\nConfidence level:",
    VAR_CONFIDENCE
)


print(
    "\nEqual Weight:"
)


print(
    "VaR 95%:",
    benchmark_var
)


print(
    "ES 95%:",
    benchmark_es
)


print(
    "\nMax-40:"
)


print(
    "VaR 95%:",
    alternative_var
)


print(
    "ES 95%:",
    alternative_es
)


# ============================================================
# 28. PORTFOLIO TAIL RISK COMPARISON
# ============================================================

tail_risk_comparison = pd.DataFrame({

    "Portfolio": [

        "Equal_Weight",

        "Max_40"

    ],

    "Historical_VaR_95%": [

        benchmark_var,

        alternative_var

    ],

    "Expected_Shortfall_95%": [

        benchmark_es,

        alternative_es

    ]
})


print(
    "\n" + "=" * 70
)

print(
    "TAIL RISK COMPARISON"
)

print(
    "=" * 70
)


print(
    tail_risk_comparison
)


# ============================================================
# 29. CREATE BENCHMARK VS ALTERNATIVE RETURN SERIES
# ============================================================

portfolio_returns = pd.DataFrame({

    "Equal_Weight":
        benchmark_returns,

    "Max_40":
        alternative_returns,

    "Active_Return":
        active_returns
})


# ============================================================
# 30. SAVE PROJECT 02 OUTPUTS
# ============================================================

performance_comparison.to_csv(

    os.path.join(

        PROJECT_02_OUTPUT,

        "performance_comparison.csv"

    ),

    index=False
)


active_weight_table.to_csv(

    os.path.join(

        PROJECT_02_OUTPUT,

        "active_weights.csv"

    )
)


performance_attribution.to_csv(

    os.path.join(

        PROJECT_02_OUTPUT,

        "performance_attribution.csv"

    )
)


risk_contribution.to_csv(

    os.path.join(

        PROJECT_02_OUTPUT,

        "risk_contribution.csv"

    )
)


portfolio_returns.to_csv(

    os.path.join(

        PROJECT_02_OUTPUT,

        "portfolio_returns.csv"

    )
)


daily_active_contribution.to_csv(

    os.path.join(

        PROJECT_02_OUTPUT,

        "daily_active_contribution.csv"

    )
)


oos_covariance.to_csv(

    os.path.join(

        PROJECT_02_OUTPUT,

        "oos_covariance_matrix.csv"

    )
)


tail_risk_comparison.to_csv(

    os.path.join(

        PROJECT_02_OUTPUT,

        "tail_risk_comparison.csv"

    ),

    index=False
)


# ============================================================
# 31. SUMMARY METRICS
# ============================================================

summary = pd.DataFrame({

    "Metric": [

        "Benchmark Total Return",

        "Alternative Total Return",

        "Active Total Return",

        "Benchmark Annualized Return",

        "Alternative Annualized Return",

        "Benchmark Volatility",

        "Alternative Volatility",

        "Benchmark Sharpe",

        "Alternative Sharpe",

        "Benchmark Maximum Drawdown",

        "Alternative Maximum Drawdown",

        "Tracking Error",

        "Information Ratio",

        "Benchmark Historical VaR 95%",

        "Alternative Historical VaR 95%",

        "Benchmark Expected Shortfall 95%",

        "Alternative Expected Shortfall 95%"

    ],


    "Value": [

        benchmark_metrics[
            "Total_Return"
        ],


        alternative_metrics[
            "Total_Return"
        ],


        active_total_return,


        benchmark_metrics[
            "Annualized_Return"
        ],


        alternative_metrics[
            "Annualized_Return"
        ],


        benchmark_metrics[
            "Annualized_Volatility"
        ],


        alternative_metrics[
            "Annualized_Volatility"
        ],


        benchmark_metrics[
            "Sharpe_Ratio"
        ],


        alternative_metrics[
            "Sharpe_Ratio"
        ],


        benchmark_metrics[
            "Maximum_Drawdown"
        ],


        alternative_metrics[
            "Maximum_Drawdown"
        ],


        annualized_tracking_error,


        information_ratio,


        benchmark_var,


        alternative_var,


        benchmark_es,


        alternative_es

    ]

})


summary.to_csv(

    os.path.join(

        PROJECT_02_OUTPUT,

        "risk_performance_summary.csv"

    ),

    index=False
)


# ============================================================
# 32. FINAL PROJECT 02 SUMMARY
# ============================================================

print(
    "\n" + "=" * 70
)

print(
    "PROJECT 02 COMPLETED"
)

print(
    "=" * 70
)


print(
    "\nBenchmark:"
)

print(
    "Equal Weight"
)


print(
    "\nAlternative:"
)

print(
    "Max-40 constrained portfolio"
)


print(
    "\nActive total return:",
    active_total_return
)


print(
    "\nTracking error:",
    annualized_tracking_error
)


print(
    "\nInformation ratio:",
    information_ratio
)


print(
    "\nEqual Weight VaR 95%:",
    benchmark_var
)


print(
    "Equal Weight ES 95%:",
    benchmark_es
)


print(
    "\nMax-40 VaR 95%:",
    alternative_var
)


print(
    "Max-40 ES 95%:",
    alternative_es
)


print(
    "\nRisk contribution:"
)


print(
    risk_contribution[
        "Risk_Contribution_%"
    ]
)


print(
    "\nProject 02 outputs saved to:"
)


print(
    PROJECT_02_OUTPUT
)


print(
    "\n" + "=" * 70
)

print(
    "PROJECT 02 — COMPLETE"
)

print(
    "=" * 70
)